from app.models import db, Post, environment, SCHEMA


def seed_posts():
  objects = [
    Post(likeable_id = 1, user_id = 1, caption = 'caption 1', location = 'Australia'),
    Post(likeable_id = 2, user_id = 1, caption = 'caption 2', location = 'Japan'),
    Post(likeable_id = 3, user_id = 1, caption = 'caption 3', location = 'Canada'),
    Post(likeable_id = 4, user_id = 1, caption = 'caption 4', location = 'Denmark'),
    Post(likeable_id = 5, user_id = 1, caption = 'caption 5', location = 'Germany'),
    Post(likeable_id = 6, user_id = 1, caption = 'caption 6', location = 'India'),
    Post(likeable_id = 7, user_id = 1, caption = 'caption 7', location = 'Hungary'),
    Post(likeable_id = 8, user_id = 1, caption = 'caption 8', location = 'China'),
    Post(likeable_id = 9, user_id = 1, caption = 'caption 9', location = 'Finland'),
    Post(likeable_id = 10, user_id = 1, caption = 'caption 10', location = 'United Kingdom'),
    Post(likeable_id = 11, user_id = 1, caption = 'caption 11', location = 'Yemen'),
    Post(likeable_id = 12, user_id = 1, caption = 'caption 12', location = 'Oman'),
    Post(likeable_id = 13, user_id = 1, caption = 'caption 14', location = 'Zimbabwe'),
    Post(likeable_id = 14, user_id = 1, caption = 'caption 15', location = 'France'),
    Post(likeable_id = 15, user_id = 1, caption = 'caption 16', location = 'Peru'),
    Post(likeable_id = 16, user_id = 1, caption = 'caption 17', location = 'Qatar'),
    Post(likeable_id = 17, user_id = 1, caption = 'caption 18', location = 'Vanuatu'),
    Post(likeable_id = 18, user_id = 1, caption = 'caption 19', location = 'Rwanda'),
    Post(likeable_id = 19, user_id = 1, caption = 'caption 20', location = 'Netherlands'),
    Post(likeable_id = 20, user_id = 2, caption = 'caption 1', location = 'Australia'),
    Post(likeable_id = 21, user_id = 2, caption = 'caption 2', location = 'Japan'),
    Post(likeable_id = 22, user_id = 2, caption = 'caption 3', location = 'Canada'),
    Post(likeable_id = 23, user_id = 2, caption = 'caption 4', location = 'Denmark'),
    Post(likeable_id = 24, user_id = 2, caption = 'caption 5', location = 'Germany'),
    Post(likeable_id = 25, user_id = 2, caption = 'caption 6', location = 'India'),
    Post(likeable_id = 26, user_id = 2, caption = 'caption 7', location = 'Hungary'),
    Post(likeable_id = 27, user_id = 2, caption = 'caption 8', location = 'China'),
    Post(likeable_id = 28, user_id = 2, caption = 'caption 9', location = 'Finland'),
    Post(likeable_id = 29, user_id = 2, caption = 'caption 10', location = 'United Kingdom'),
    Post(likeable_id = 30, user_id = 2, caption = 'caption 11', location = 'Yemen'),
    Post(likeable_id = 31, user_id = 2, caption = 'caption 12', location = 'Oman'),
    Post(likeable_id = 32, user_id = 2, caption = 'caption 14', location = 'Zimbabwe'),
    Post(likeable_id = 33, user_id = 2, caption = 'caption 15', location = 'France'),
    Post(likeable_id = 34, user_id = 2, caption = 'caption 16', location = 'Peru'),
    Post(likeable_id = 35, user_id = 2, caption = 'caption 17', location = 'Qatar'),
    Post(likeable_id = 36, user_id = 2, caption = 'caption 18', location = 'Vanuatu'),
    Post(likeable_id = 37, user_id = 2, caption = 'caption 19', location = 'Rwanda'),
    Post(likeable_id = 38, user_id = 2, caption = 'caption 20', location = 'Netherlands'),
    Post(likeable_id = 39, user_id = 3, caption = 'caption 1', location = 'Australia'),
    Post(likeable_id = 40, user_id = 3, caption = 'caption 2', location = 'Japan'),
    Post(likeable_id = 41, user_id = 3, caption = 'caption 3', location = 'Canada'),
    Post(likeable_id = 42, user_id = 3, caption = 'caption 4', location = 'Denmark'),
    Post(likeable_id = 43, user_id = 3, caption = 'caption 5', location = 'Germany'),
    Post(likeable_id = 44, user_id = 3, caption = 'caption 6', location = 'India'),
    Post(likeable_id = 45, user_id = 3, caption = 'caption 7', location = 'Hungary'),
    Post(likeable_id = 46, user_id = 3, caption = 'caption 8', location = 'China'),
    Post(likeable_id = 47, user_id = 3, caption = 'caption 9', location = 'Finland'),
    Post(likeable_id = 48, user_id = 3, caption = 'caption 10', location = 'United Kingdom'),
    Post(likeable_id = 49, user_id = 3, caption = 'caption 11', location = 'Yemen'),
    Post(likeable_id = 50, user_id = 3, caption = 'caption 12', location = 'Oman'),
    Post(likeable_id = 51, user_id = 3, caption = 'caption 14', location = 'Zimbabwe'),
    Post(likeable_id = 52, user_id = 3, caption = 'caption 15', location = 'France'),
    Post(likeable_id = 53, user_id = 3, caption = 'caption 16', location = 'Peru'),
    Post(likeable_id = 54, user_id = 3, caption = 'caption 17', location = 'Qatar'),
    Post(likeable_id = 55, user_id = 3, caption = 'caption 18', location = 'Vanuatu'),
    Post(likeable_id = 56, user_id = 3, caption = 'caption 19', location = 'Rwanda'),
    Post(likeable_id = 57, user_id = 3, caption = 'caption 20', location = 'Netherlands'),
    Post(likeable_id = 58, user_id = 4, caption = 'caption 1', location = 'Australia'),
    Post(likeable_id = 59, user_id = 4, caption = 'caption 2', location = 'Japan'),
    Post(likeable_id = 60, user_id = 4, caption = 'caption 3', location = 'Canada'),
    Post(likeable_id = 61, user_id = 4, caption = 'caption 4', location = 'Denmark'),
    Post(likeable_id = 62, user_id = 4, caption = 'caption 5', location = 'Germany'),
    Post(likeable_id = 63, user_id = 4, caption = 'caption 6', location = 'India'),
    Post(likeable_id = 64, user_id = 4, caption = 'caption 7', location = 'Hungary'),
    Post(likeable_id = 65, user_id = 4, caption = 'caption 8', location = 'China'),
    Post(likeable_id = 66, user_id = 4, caption = 'caption 9', location = 'Finland'),
    Post(likeable_id = 67, user_id = 4, caption = 'caption 10', location = 'United Kingdom'),
    Post(likeable_id = 68, user_id = 4, caption = 'caption 11', location = 'Yemen'),
    Post(likeable_id = 69, user_id = 4, caption = 'caption 12', location = 'Oman'),
    Post(likeable_id = 70, user_id = 4, caption = 'caption 14', location = 'Zimbabwe'),
    Post(likeable_id = 71, user_id = 4, caption = 'caption 15', location = 'France'),
    Post(likeable_id = 72, user_id = 4, caption = 'caption 16', location = 'Peru'),
    Post(likeable_id = 73, user_id = 4, caption = 'caption 17', location = 'Qatar'),
    Post(likeable_id = 74, user_id = 4, caption = 'caption 18', location = 'Vanuatu'),
    Post(likeable_id = 75, user_id = 4, caption = 'caption 19', location = 'Rwanda'),
    Post(likeable_id = 76, user_id = 4, caption = 'caption 20', location = 'Netherlands'),
    Post(likeable_id = 77, user_id = 5, caption = 'caption 1', location = 'Australia'),
    Post(likeable_id = 78, user_id = 5, caption = 'caption 2', location = 'Japan'),
    Post(likeable_id = 79, user_id = 5, caption = 'caption 3', location = 'Canada'),
    Post(likeable_id = 80, user_id = 5, caption = 'caption 4', location = 'Denmark'),
    Post(likeable_id = 81, user_id = 5, caption = 'caption 5', location = 'Germany'),
    Post(likeable_id = 82, user_id = 5, caption = 'caption 6', location = 'India'),
    Post(likeable_id = 83, user_id = 5, caption = 'caption 7', location = 'Hungary'),
    Post(likeable_id = 84, user_id = 5, caption = 'caption 8', location = 'China'),
    Post(likeable_id = 85, user_id = 5, caption = 'caption 9', location = 'Finland'),
    Post(likeable_id = 86, user_id = 5, caption = 'caption 10', location = 'United Kingdom'),
    Post(likeable_id = 87, user_id = 5, caption = 'caption 11', location = 'Yemen'),
    Post(likeable_id = 88, user_id = 5, caption = 'caption 12', location = 'Oman'),
    Post(likeable_id = 89, user_id = 5, caption = 'caption 14', location = 'Zimbabwe'),
    Post(likeable_id = 90, user_id = 5, caption = 'caption 15', location = 'France'),
    Post(likeable_id = 91, user_id = 5, caption = 'caption 16', location = 'Peru'),
    Post(likeable_id = 92, user_id = 5, caption = 'caption 17', location = 'Qatar'),
    Post(likeable_id = 93, user_id = 5, caption = 'caption 18', location = 'Vanuatu'),
    Post(likeable_id = 94, user_id = 5, caption = 'caption 19', location = 'Rwanda'),
    Post(likeable_id = 95, user_id = 5, caption = 'caption 20', location = 'Netherlands')
  ]
  db.session.add_all(objects)
  db.session.commit()


def undo_posts():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.posts RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM posts")

    db.session.commit()
